### ISSUE TITLE
Collect and clean Medicare Part B spending data

### ISSUE THREAD

**Issue by mattgawarecki** [Data4Democracy/drug-spending#17]
# Task
Download the [Part B spending data](https://www.cms.gov/Research-Statistics-Data-and-Systems/Statistics-Trends-and-Reports/Information-on-Prescription-Drugs/2015MedicareData.html) from CMS and convert it to an accessible format that's easier to analyze.

# How this will help
Part D is a large component of drug spending with respect to Medicare, but Part B is significant, as well. If we incorporate Part B statistics into our decision-making and analyses, we can make comparisons and get a better picture for Medicare drug spending as a whole.

**Comment by sgalletta213** [comment]
Done!  Made a commit for the data and code.

**Comment by mattgawarecki** [comment]
Closing this issue since we merged #20. Great work, @sgalletta213! 👍
