### ISSUE TITLE
Find drugs with the largest year-over-year increases in claims, spending

### ISSUE THREAD

**Issue by mattgawarecki** [Data4Democracy/drug-spending#18]
# Task
Analyze all available data to determine which drugs and/or types of drugs show the biggest year-over-year increases in claims and spending (total and/or per-user).

# How this will help
If we can understand which medicines are being used more often, it gives us more ideas as to how America's health issues continue to evolve. Using this information, we can ask deeper questions and search for ways to improve the quality of healthcare for millions of Americans.

**Comment by davidlibland** [comment]
I'd be happy to help with this task. I've started looking at this for the data in the github directory part_b_spend_clean/output/part_b_spend_clean.csv
Is that the data I should be looking at?

**Comment by jenniferthompson** [comment]
@davidlibland Hi! We've mostly been looking at part D so far, but I imagine the question would apply to both B and D. Thanks for getting it started! We'd love to have you in the [Slack channel](https://datafordemocracy.slack.com/messages/drug-spending/) - I just tried to invite you and save you a step, but it won't let me for some reason.

**Comment by mattgawarecki** [comment]
@jenniferthompson I took care of the channel invite just now. :-)

@davidlibland: If you're comfortable with it, I think it would be useful to get comparisons for both Part B and D like @jenniferthompson suggests. You can find the data for Part D at https://data.world/data4democracy/drug-spending -- they're the files named `spending-{year}.*`, and they should be available in both CSV and feather format.

**Comment by mattgawarecki** [comment]
@davidlibland With PR #42, is this issue complete? Or did you have plans for further awesomeness? :smile:

**Comment by davidlibland** [comment]
Dear Matt,
I feel like it is complete for now; until we have a better idea of how to incorporate it into the greater project...

- david

**Comment by mattgawarecki** [comment]
Alrighty! I'm going to close this issue for now, and as we get ideas for how to move forward, we can create new issues to track those efforts.
