### ISSUE TITLE
Investigate new data source: Medical Expenditure Panel Survey

### ISSUE THREAD

**Issue by mrklees** [Data4Democracy/drug-spending#22]
# Task
Data is annually collected by the Agency for Healthcare Research and Quality that is used to make nationally representative estimates of health care use, expenditures, sources of payment, and health insurance coverage.  Investigate the website housing all of this data, [meps.ahrq.gov](https://meps.ahrq.gov/mepsweb/data_stats/download_data_files.jsp), and find any data files which include details on prescription drug spending. 

# How this will help
The data available on the site could help us understand the trends in prescription drug spending over the last decade. It could help add context to our analysis as well, as the data is not limited to Medicaid and Medicare recipients.

# What we want to get out of this
The data we're interested on is a subset of what is available, so a first task might be to compile a list of names and descriptions of the data of interest. Some of the data sets have nearly 2000 features in the data, so it would also be very helpful if fields of interest were identified for each data set and clearly documented.

**Comment by jenniferthompson** [comment]
Awesome - thanks @mrklees!

**Comment by mrklees** [comment]
I have begun to document the data available on meps.ahrq.gov in [this google sheet](https://docs.google.com/spreadsheets/d/1zZVzO9e_y9hXnpoEcFBOlJC_cjVeyw0JWJxTiiq2Its/edit?usp=sharing).

Update:
If anyone is looking for a way to collaborate on this, a good way would be to open up the google sheet and the navigate to the documentation of the 2014 Full Year consolidated data file.  Then dig through it and try to find any fields that might be interesting in future analysis.  There are 1839 features, so there's plenty to consider.

**Comment by mtelpoukhovskaia** [comment]
@mrklees, I see there are 43 fields of interest that you've identified.  Are you currently looking for more , or working on tidying the data? I can help out on this issue.

**Comment by jenniferthompson** [comment]
@mtelpoukhovskaia I'm not aware of any further work that's been done @mrklees's post, so if you'd like to run with this that would be great!

**Comment by mrklees** [comment]
Hi @mtelpoukhovskaia, sorry for being unresponsive.  The most interesting data I have found through MEPS is the Prescribed Medicine Files (link in the gsheet).  It tracks patient spending and consumption of individual drugs along with a ton of demographic markers and other fields.  I have been working towards trying to combine all data from 1996 to 2014 into a single data file, but I have had a lot of trouble cleaning the data.  Here are a couple things that would be super helpful: 

*  Trying to successfully merge fields across the 16 years of data. Some fields have gotten dropped or re-coded over the years, and need to be mapped. 
*  Investigating the ids used in each file.  Unfortunately, I don't think they have a primary key that works across years, so we will need to construct it. 

Tonight I will upload the work that I've done to my fork of the repo so that you can see what work I've already done.

**Comment by mattgawarecki** [comment]
@mrklees @mtelpoukhovskaia Checking in to see how work on this issue is going. If either of you has run into any obstacles, we'll do what we can to help. 👍

**Comment by darya-akimova** [comment]
While the MEPS survey is uploaded on data.world, I'm not sure how it can be used at the current project step. Will close this issue for now and open a new one if there seems to be a use for it in the future.
