### ISSUE TITLE
Create glossary of terms found in our datasets/context

### ISSUE THREAD

**Issue by jenniferthompson** [Data4Democracy/drug-spending#38]
Healthcare has lots of abbreviations, acronyms and terms. Most of us don't know them all. We need a glossary to help us understand them. Ideally, we'd have a format like:

1. *term*: quick description. Link(s) for more info.
1. *RxNorm*: normalized names for clinical drugs to enable linking between sources. [More info: NIH/National Library of Medicine](https://www.nlm.nih.gov/research/umls/rxnorm/).

Terms we've come across so far:
- RxNorm
- NDC
- Medicare
- Medicaid
- HCPCS

Add others below and I'll update the above list.

**Comment by mattgrieser** [comment]
I'd love to help with this. Where would this glossary ideally live?

**Comment by jenniferthompson** [comment]
@mattgrieser The goal is to have it as a Markdown document in our `/docs` folder here (Github is our central repository for everything except our data, which lives on data.world). Thank you! This will be great.

**Comment by mattgawarecki** [comment]
@mattgrieser Just checking in -- how's work on the glossary? We're all obviously volunteers so there's no pressure to deliver, I'm just curious if there's anything you need or if there are any obstacles we could help clear for you 😄

**Comment by mattgrieser** [comment]
@mattgawarecki I have completed the initial document in '/docs', but would love to figure out a smooth way to find and add new terms.

**Comment by mattgawarecki** [comment]
@mattgrieser What would you like to see in the way of smoothness? Do you envision something more substantial to track these sorts of definitions, like a web app? Or maybe something simpler but with less Git involvement?

**Comment by mattgrieser** [comment]
@mattgawarecki Git would work fine. If people could post terms in need of definition here (or some central place), we could have people work on quick definitions.

**Comment by jenniferthompson** [comment]
I think a lot of them come up in the discussion on Slack, but this is a better repository for to-do items, so perhaps a combo approach would work well: someone asks about a term, one of us makes sure to add it here so it can be worked on?

**Comment by darya-akimova** [comment]
This is something that can be done as we go along, but probably doesn't need its own separate issue.
