### ISSUE TITLE
Add datasets collected & cleaned by `read_data.py` to data.world

### ISSUE THREAD

**Issue by jenniferthompson** [Data4Democracy/drug-spending#40]
`read_data.py` collects and tidies several datasets not currently available on data.world - we need to add these to the data.world repo + document them here for use by all.

**Comment by mattgawarecki** [comment]
Just going through the issues board and making sure everything's up to date -- how are we on this one? I want to say it seems like everything's up on data.world right now, but I'm not certain. @dhuppenkothen or @jenniferthompson, perhaps either of you would know more?

**Comment by dhuppenkothen** [comment]
No, I'm pretty sure that there are files missing (since I certainly didn't upload them yet). 
Sorry for dropping the ball on this; real life took precedence for a while. I've started generating the data sets for upload, but making the data dictionaries is taking a while longer.

**Comment by mattgawarecki** [comment]
No worries! We're all volunteers here! :grin:
