### ISSUE TITLE
Create visualization to help understand physician/hospital payments

### ISSUE THREAD

**Issue by jenniferthompson** [Data4Democracy/drug-spending#46]
OpenPaymentsData.CMS.gov has data available on physician and teaching hospital payments from pharmaceutical and device companies. We'd like to explore it to see information like...

* How do patterns vary by physician specialty?
* How have payment patterns changed over time?
* other questions of interest

Note that this is blocked until issue #45 is completed.

**Comment by kimkraunz** [comment]
Would love to work on this when #45 is complete.

**Comment by veenaghorakavi** [comment]
I can work on this.
