### ISSUE TITLE
Visualize/describe how payroll taxes are allocated when funding Medicare Part A

### ISSUE THREAD

**Issue by jenniferthompson** [Data4Democracy/drug-spending#47]
[Medicare Part A](https://www.medicare.gov/what-medicare-covers/part-a/what-part-a-covers.html) is the only piece of Medicare funded directly by payroll taxes. We'd like to show how each tax dollar is spent on different categories of expenditure: home health care, skilled nursing facilities, hospital stays, etc.

**Comment by jenniferthompson** [comment]
@mattgawarecki Do you have a link for the Medicare Part A report source?

**Comment by mattgawarecki** [comment]
@jenniferthompson Somehow I missed this issue -- sorry! 😞 

A report gets drafted each year by the Medicare Board of Trustees to explain the status of Medicare's trust fund and other budgetary concerns. There's lots and lots of information in the report for anyone who feels like giving it a look. It's published on CMS.gov; you can find the latest issue for 2016 here:

[2016 ANNUAL REPORT OF THE BOARDS OF TRUSTEES OF THE FEDERAL HOSPITAL INSURANCE AND FEDERAL SUPPLEMENTARY MEDICAL INSURANCE TRUST FUNDS](https://www.cms.gov/Research-Statistics-Data-and-Systems/Statistics-Trends-and-Reports/ReportsTrustFunds/Downloads/TR2016.pdf)

For a detailed look at where Medicare Part A's money is coming from, skip to page 10 of the report (or page 16 of the PDF itself). It'll have a table that lists income for the year, grouped by respective sources.
