### ISSUE TITLE
Visualize/model relationship between lobbying expenditures and brand name prices

### ISSUE THREAD

**Issue by jenniferthompson** [Data4Democracy/drug-spending#48]
We have [data from OpenSecrets](https://github.com/Data4Democracy/drug-spending/tree/master/datadictionaries) on lobbying expenditures from pharmaceutical companies, and keys are in progress to join this with Medicare Part D spending data (see issue #37). Once we can join these datasets, we'd like to see if there is a relationship between lobbying expenditures and Medicare costs for those companies' medications.

**Comment by mallaham** [comment]
I'm interested in this project :)

**Comment by jenniferthompson** [comment]
@mallaham you should have an invitation to join the D4D organization; once you do that I can assign you!

**Comment by mallaham** [comment]
done!

**Comment by atamalu** [comment]
I am interested in this project. Or really anything regarding drug lobbying expenditures

**Comment by yanoak** [comment]
would be happy to help with data visualisation work on this project.

**Comment by andypicke** [comment]
I'm interested in helping. Is the data ready to be modeled, or is there more data collection/tidying that needs to be done first?

**Comment by jenniferthompson** [comment]
Hi @atamalu, @yanoak and @andypicke! All the data we have cleaned and ready to go is in our [repo on data.world](https://data.world/data4democracy/drug-spending). You're welcome to see what interests you there! We haven't gotten the keys for lobbying and Medicare ready, unfortunately. The code for lobbying vs manufacturer keys is [in our repo here](https://github.com/Data4Democracy/drug-spending/tree/master/R/datawrangling/manufacturers); if any of you would like to take a look and work on finishing up the keys we'd welcome that too.

**Comment by andypicke** [comment]
thanks @jenniferthompson  . I'm going to start looking at some of the data, starting with 'spending_all_top100.csv' . Should I upload my notebook to the 'analysis-viz' folder?

**Comment by jenniferthompson** [comment]
@andypicke Definitely, under whichever language you're using (we have `R/` and `python/` so far). That would be great!

**Comment by andypicke** [comment]
@jenniferthompson  - Is the best way to do that to fork, add my notebook, and then pull request? Sorry, haven't worked on collaborative git projects much before.

**Comment by jenniferthompson** [comment]
@andypicke Exactly! I hear you - D4D was my first major experience with git collaboration, and it's a great way to learn it. There's also a #github-help channel on the Slack team if you run into any trouble!

**Comment by AbhijithReddy** [comment]
Hi I have registered with D4D recently and even joined the slack channel. I'd like to work on a modelling model but as I am new  would love to have some mentorship.
Thanks in advance.
