### ISSUE TITLE
Join Medicare Part D spending data to ATC Classification System

### ISSUE THREAD

**Issue by darya-akimova** [Data4Democracy/drug-spending#76]
## Status

- @darwinyfu has expressed interest in working on this problem
- Ongoing: @Anandkarthick has made progress on this issue by matching the spending files to `drug_uses.csv` (on data.world) by the `drugname_generic`

### Update:
- Upon working with it, I've discovered that `drug_uses.csv` is missing drugs that should be in the ATC system (and are present in the `atc_codes_clean.csv` dataset). It seems that the `atc_codes_clean.csv` is the way to go, even though it's currently in a messier state.

#### Update 3/1/2018
Matched app. 3k out of 4.5k items in the Medicare Part D dataset (see /drug-spending/R/datawrangling/atc_merge_atc_codes_clean_da and /atc_merge_drug_uses_csv_da for notebook), but putting this issue on hold and switching directions because:
- ATC classification offers limited matching on brand name. While it is possible to get some successful matches based on the generic/chemical names, this approach becomes complicated for drugs with multiple active ingredients
- Unsure how to combine multiple ATC code assignments, both for single compounds that have multiple ATC classifications and for drugs with multiple (2-8) active ingredients. 
- Started hitting a wall where a lot of research and hand annotation would be required to make progress

## Task

Join drugs in the Medicare Part D spending data to their ATC Classification System categories by join the `spending-201x.csv` files on data.world to either `atc_codes_clean.csv` <s>or `drug_uses.csv`.</s>

### Potential outputs that would help greatly to further the goal of this project:
- A csv file of the two joined files if able to match all of the drugs in the Medicare spending files to ATC classification categories
OR both of the following (because the above will probably be challenging and/or a big time investment for one person): 
- A work in progress csv file with all successfully matched drugs 
- A work in progress csv file containing all of the drugs that COULD NOT be matched

#### `atc_codes_clean.csv` dataset
- Match the `drugname_generic` column from any of the `spending-201x.csv` files on data.world to the `atc_codes_clean.csv` file on data.world by the `level5` or `kegg` columns. But these columns are very messy in the `atc_codes_clean.csv` file. To be honest I didn't put in much effort into cleaning them because I wasn't sure how these columns would be used down the line. 

<s>OR

#### `drug_uses.csv` dataset (which may be the easier of the two)
Two options: 
- Join the `drugname_brand` column in any of the `spending-201x.csv` datasets to the `drugname_brand` column in `drug_uses.csv`. 
OR
- Match the `drugname_generic` column from any of the `spending-201x.csv` files on data.world to the  `drugname_generic` or `substance` or `name` columns in `drug_uses.csv`. These columns in the `drug_uses.csv` dataset are much cleaner than the `atc_codes_clean.csv` and I only realized that this file contained ATC classification information after I uploaded the `atc_codes_clean.csv`. </s>

Side note: all of the `spending-201x.csv` files should have the same drugs in the same format, since they come from a parent wide .xlsx file that had the years data spread across the columns. If the drugs from one of the spending files are matched successfully, then the same steps should successfully join the other files, so no need to try and compare all of the spending files to find differences in drug names.

### Ideal file formats for the analysis:
- Jupyter notebook with code outputs
OR
- R Markdown file (ideally knitted to html) with code outputs

## How this will help

We're working towards matching drugs to their therapeutic uses. The USP Classification system, FDA drug approval data, and the ATC Classification system seem to be the best potential grouping categories of drugs from the datasets that have already been collected. The ATC classifications system provides classification seems to be more scientific/medical jargon-leaning, but it can be potentially useful down the line.

**Comment by Anandkarthick** [comment]
I just completed this task for one dataset.. spending_2011. How can I share the dataset? just wanted to get a comment before doing this for all dataset.

**Comment by SeniorHealthcareAdvisors** [comment]
When CMS overhauls its Electronic Health Record (EHR) how will it affect
 [supplemental health insurance costs & Medicare Open Enrollment 2019?](http://www.seniorhealthcareadv.com)
